services:
  - type: web
    name: southernbites
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/SouthernBites-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
